# Generated by Django 2.2.4 on 2019-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_warangaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='warangaldetails',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
